development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  pool: 5
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  pool: 5
  host: localhost