development:
  adapter: postgresql
  encoding: unicode
  database: urlshortener-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: urlshortener-test
  pool: 5
  port: 5432
  host: localhost